#include "format.hpp"
#include "device.hpp"

namespace slrd {
    VkFormat getVkFormat (slrd::Format format) {
#define __FORMAT_CASE(__Internal, __Vk) \
        case __Internal: vkformat = __Vk; break;

        VkFormat vkformat = VK_FORMAT_UNDEFINED;

        switch (format) {
            case FORMAT_UNDEFINED:
                break;

            __FORMAT_CASE (FORMAT_RGBA8_UNORM,    VK_FORMAT_R8G8B8A8_UNORM);
            __FORMAT_CASE (FORMAT_RGBA8_SNORM,    VK_FORMAT_R8G8B8A8_SNORM);
            __FORMAT_CASE (FORMAT_RGBA8_UINT,     VK_FORMAT_R8G8B8A8_UINT);
            __FORMAT_CASE (FORMAT_RGBA8_SINT,     VK_FORMAT_R8G8B8A8_SINT);
            __FORMAT_CASE (FORMAT_RGBA8_SRGB,     VK_FORMAT_R8G8B8A8_SRGB);

            __FORMAT_CASE (FORMAT_RGBA16_UNORM,   VK_FORMAT_R16G16B16A16_UNORM);
            __FORMAT_CASE (FORMAT_RGBA16_SNORM,   VK_FORMAT_R16G16B16A16_SNORM);
            __FORMAT_CASE (FORMAT_RGBA16_SFLOAT,  VK_FORMAT_R16G16B16A16_SFLOAT);
            __FORMAT_CASE (FORMAT_RGBA16_UINT,    VK_FORMAT_R16G16B16A16_UINT);
            __FORMAT_CASE (FORMAT_RGBA16_SINT,    VK_FORMAT_R16G16B16A16_SINT);

            __FORMAT_CASE (FORMAT_RGBA32_SFLOAT,  VK_FORMAT_R32G32B32A32_SFLOAT);
            __FORMAT_CASE (FORMAT_RGBA32_UINT,    VK_FORMAT_R32G32B32A32_UINT);
            __FORMAT_CASE (FORMAT_RGBA32_SINT,    VK_FORMAT_R32G32B32A32_SINT);

            __FORMAT_CASE (FORMAT_BGRA8_UNORM,    VK_FORMAT_B8G8R8A8_UNORM);
            __FORMAT_CASE (FORMAT_BGRA8_SRGB,     VK_FORMAT_B8G8R8A8_SRGB);

            __FORMAT_CASE (FORMAT_RGB32_SFLOAT,  VK_FORMAT_R32G32B32_SFLOAT);
            __FORMAT_CASE (FORMAT_RGB32_UINT,    VK_FORMAT_R32G32B32_UINT);
            __FORMAT_CASE (FORMAT_RGB32_SINT,    VK_FORMAT_R32G32B32_SINT);

            __FORMAT_CASE (FORMAT_RG8_UNORM,     VK_FORMAT_R8G8_UNORM);
            __FORMAT_CASE (FORMAT_RG8_SNORM,     VK_FORMAT_R8G8_SNORM);
            __FORMAT_CASE (FORMAT_RG8_UINT,      VK_FORMAT_R8G8_UINT);
            __FORMAT_CASE (FORMAT_RG8_SINT,      VK_FORMAT_R8G8_SINT);

            __FORMAT_CASE (FORMAT_RG16_UNORM,    VK_FORMAT_R16G16_UNORM);
            __FORMAT_CASE (FORMAT_RG16_SNORM,    VK_FORMAT_R16G16_SNORM);
            __FORMAT_CASE (FORMAT_RG16_SFLOAT,   VK_FORMAT_R16G16_SFLOAT);
            __FORMAT_CASE (FORMAT_RG16_UINT,     VK_FORMAT_R16G16_UINT);
            __FORMAT_CASE (FORMAT_RG16_SINT,     VK_FORMAT_R16G16_SINT);

            __FORMAT_CASE (FORMAT_RG32_SFLOAT,   VK_FORMAT_R32G32_SFLOAT);
            __FORMAT_CASE (FORMAT_RG32_UINT,     VK_FORMAT_R32G32_UINT);
            __FORMAT_CASE (FORMAT_RG32_SINT,     VK_FORMAT_R32G32_SINT);

            __FORMAT_CASE (FORMAT_R8_UNORM,      VK_FORMAT_R8_UNORM);
            __FORMAT_CASE (FORMAT_R8_SNORM,      VK_FORMAT_R8_SNORM);
            __FORMAT_CASE (FORMAT_R8_UINT,       VK_FORMAT_R8_UINT);
            __FORMAT_CASE (FORMAT_R8_SINT,       VK_FORMAT_R8_SINT);

            __FORMAT_CASE (FORMAT_R16_UNORM,     VK_FORMAT_R16_UNORM);
            __FORMAT_CASE (FORMAT_R16_SNORM,     VK_FORMAT_R16_SNORM);
            __FORMAT_CASE (FORMAT_R16_SFLOAT,    VK_FORMAT_R16_SFLOAT);
            __FORMAT_CASE (FORMAT_R16_UINT,      VK_FORMAT_R16_UINT);
            __FORMAT_CASE (FORMAT_R16_SINT,      VK_FORMAT_R16_SINT);

            __FORMAT_CASE (FORMAT_R32_SFLOAT,   VK_FORMAT_R32_SFLOAT);
            __FORMAT_CASE (FORMAT_R32_UINT,     VK_FORMAT_R32_UINT);
            __FORMAT_CASE (FORMAT_R32_SINT,     VK_FORMAT_R32_SINT);

            __FORMAT_CASE (FORMAT_RGB10A2_UINT,  VK_FORMAT_A2R10G10B10_UINT_PACK32);
            __FORMAT_CASE (FORMAT_RGB10A2_UNORM, VK_FORMAT_A2R10G10B10_UNORM_PACK32);

            __FORMAT_CASE (FORMAT_RG11B10_UFLOAT, VK_FORMAT_B10G11R11_UFLOAT_PACK32);

            __FORMAT_CASE (FORMAT_BC1_RGB_UNORM, VK_FORMAT_BC1_RGB_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGB_SRGB, VK_FORMAT_BC1_RGB_SRGB_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGBA_UNORM, VK_FORMAT_BC1_RGBA_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGBA_SRGB, VK_FORMAT_BC1_RGBA_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_BC3_UNORM, VK_FORMAT_BC3_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC3_SRGB, VK_FORMAT_BC3_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_BC4_UNORM, VK_FORMAT_BC4_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC4_SNORM, VK_FORMAT_BC4_SNORM_BLOCK);

            __FORMAT_CASE (FORMAT_BC5_UNORM, VK_FORMAT_BC5_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC5_SNORM, VK_FORMAT_BC5_SNORM_BLOCK);

            __FORMAT_CASE (FORMAT_BC6H_UFLOAT, VK_FORMAT_BC6H_UFLOAT_BLOCK);
            __FORMAT_CASE (FORMAT_BC6H_SFLOAT, VK_FORMAT_BC6H_SFLOAT_BLOCK);

            __FORMAT_CASE (FORMAT_BC7_UNORM, VK_FORMAT_BC7_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC7_SRGB, VK_FORMAT_BC7_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_D16_UNORM,          VK_FORMAT_D16_UNORM);
            __FORMAT_CASE (FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT);
            __FORMAT_CASE (FORMAT_D32_SFLOAT,         VK_FORMAT_D32_SFLOAT);
            __FORMAT_CASE (FORMAT_D24_UNORM_S8_UINT,  VK_FORMAT_D24_UNORM_S8_UINT);

            default:
                SLRD_DEBUG_CRIT ("getVkFormat: invalid enum");
                break;
        }
#undef __FORMAT_CASE

        return vkformat;
    }

    slrd::Format getSLRDFormat (VkFormat vkformat) {
#define __FORMAT_CASE(__Internal, __Vk) \
        case __Vk: format = __Internal; break;

        slrd::Format format = FORMAT_UNDEFINED;

        switch (vkformat) {
            case VK_FORMAT_UNDEFINED:
                break;

            __FORMAT_CASE (FORMAT_RGBA8_UNORM,    VK_FORMAT_R8G8B8A8_UNORM);
            __FORMAT_CASE (FORMAT_RGBA8_SNORM,    VK_FORMAT_R8G8B8A8_SNORM);
            __FORMAT_CASE (FORMAT_RGBA8_UINT,     VK_FORMAT_R8G8B8A8_UINT);
            __FORMAT_CASE (FORMAT_RGBA8_SINT,     VK_FORMAT_R8G8B8A8_SINT);
            __FORMAT_CASE (FORMAT_RGBA8_SRGB,     VK_FORMAT_R8G8B8A8_SRGB);

            __FORMAT_CASE (FORMAT_RGBA16_UNORM,   VK_FORMAT_R16G16B16A16_UNORM);
            __FORMAT_CASE (FORMAT_RGBA16_SNORM,   VK_FORMAT_R16G16B16A16_SNORM);
            __FORMAT_CASE (FORMAT_RGBA16_SFLOAT,  VK_FORMAT_R16G16B16A16_SFLOAT);
            __FORMAT_CASE (FORMAT_RGBA16_UINT,    VK_FORMAT_R16G16B16A16_UINT);
            __FORMAT_CASE (FORMAT_RGBA16_SINT,    VK_FORMAT_R16G16B16A16_SINT);

            __FORMAT_CASE (FORMAT_RGBA32_SFLOAT,  VK_FORMAT_R32G32B32A32_SFLOAT);
            __FORMAT_CASE (FORMAT_RGBA32_UINT,    VK_FORMAT_R32G32B32A32_UINT);
            __FORMAT_CASE (FORMAT_RGBA32_SINT,    VK_FORMAT_R32G32B32A32_SINT);

            __FORMAT_CASE (FORMAT_BGRA8_UNORM,    VK_FORMAT_B8G8R8A8_UNORM);
            __FORMAT_CASE (FORMAT_BGRA8_SRGB,     VK_FORMAT_B8G8R8A8_SRGB);

            __FORMAT_CASE (FORMAT_RGB32_SFLOAT,  VK_FORMAT_R32G32B32_SFLOAT);
            __FORMAT_CASE (FORMAT_RGB32_UINT,    VK_FORMAT_R32G32B32_UINT);
            __FORMAT_CASE (FORMAT_RGB32_SINT,    VK_FORMAT_R32G32B32_SINT);

            __FORMAT_CASE (FORMAT_RG8_UNORM,     VK_FORMAT_R8G8_UNORM);
            __FORMAT_CASE (FORMAT_RG8_SNORM,     VK_FORMAT_R8G8_SNORM);
            __FORMAT_CASE (FORMAT_RG8_UINT,      VK_FORMAT_R8G8_UINT);
            __FORMAT_CASE (FORMAT_RG8_SINT,      VK_FORMAT_R8G8_SINT);

            __FORMAT_CASE (FORMAT_RG16_UNORM,    VK_FORMAT_R16G16_UNORM);
            __FORMAT_CASE (FORMAT_RG16_SNORM,    VK_FORMAT_R16G16_SNORM);
            __FORMAT_CASE (FORMAT_RG16_SFLOAT,   VK_FORMAT_R16G16_SFLOAT);
            __FORMAT_CASE (FORMAT_RG16_UINT,     VK_FORMAT_R16G16_UINT);
            __FORMAT_CASE (FORMAT_RG16_SINT,     VK_FORMAT_R16G16_SINT);

            __FORMAT_CASE (FORMAT_RG32_SFLOAT,   VK_FORMAT_R32G32_SFLOAT);
            __FORMAT_CASE (FORMAT_RG32_UINT,     VK_FORMAT_R32G32_UINT);
            __FORMAT_CASE (FORMAT_RG32_SINT,     VK_FORMAT_R32G32_SINT);

            __FORMAT_CASE (FORMAT_R8_UNORM,      VK_FORMAT_R8_UNORM);
            __FORMAT_CASE (FORMAT_R8_SNORM,      VK_FORMAT_R8_SNORM);
            __FORMAT_CASE (FORMAT_R8_UINT,       VK_FORMAT_R8_UINT);
            __FORMAT_CASE (FORMAT_R8_SINT,       VK_FORMAT_R8_SINT);

            __FORMAT_CASE (FORMAT_R16_UNORM,     VK_FORMAT_R16_UNORM);
            __FORMAT_CASE (FORMAT_R16_SNORM,     VK_FORMAT_R16_SNORM);
            __FORMAT_CASE (FORMAT_R16_SFLOAT,    VK_FORMAT_R16_SFLOAT);
            __FORMAT_CASE (FORMAT_R16_UINT,      VK_FORMAT_R16_UINT);
            __FORMAT_CASE (FORMAT_R16_SINT,      VK_FORMAT_R16_SINT);

            __FORMAT_CASE (FORMAT_R32_SFLOAT,   VK_FORMAT_R32_SFLOAT);
            __FORMAT_CASE (FORMAT_R32_UINT,     VK_FORMAT_R32_UINT);
            __FORMAT_CASE (FORMAT_R32_SINT,     VK_FORMAT_R32_SINT);

            __FORMAT_CASE (FORMAT_RGB10A2_UINT,  VK_FORMAT_A2R10G10B10_UINT_PACK32);
            __FORMAT_CASE (FORMAT_RGB10A2_UNORM, VK_FORMAT_A2R10G10B10_UNORM_PACK32);

            __FORMAT_CASE (FORMAT_RG11B10_UFLOAT, VK_FORMAT_B10G11R11_UFLOAT_PACK32);

            __FORMAT_CASE (FORMAT_BC1_RGB_UNORM, VK_FORMAT_BC1_RGB_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGB_SRGB, VK_FORMAT_BC1_RGB_SRGB_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGBA_UNORM, VK_FORMAT_BC1_RGBA_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC1_RGBA_SRGB, VK_FORMAT_BC1_RGBA_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_BC3_UNORM, VK_FORMAT_BC3_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC3_SRGB, VK_FORMAT_BC3_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_BC4_UNORM, VK_FORMAT_BC4_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC4_SNORM, VK_FORMAT_BC4_SNORM_BLOCK);

            __FORMAT_CASE (FORMAT_BC5_UNORM, VK_FORMAT_BC5_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC5_SNORM, VK_FORMAT_BC5_SNORM_BLOCK);

            __FORMAT_CASE (FORMAT_BC6H_UFLOAT, VK_FORMAT_BC6H_UFLOAT_BLOCK);
            __FORMAT_CASE (FORMAT_BC6H_SFLOAT, VK_FORMAT_BC6H_SFLOAT_BLOCK);

            __FORMAT_CASE (FORMAT_BC7_UNORM, VK_FORMAT_BC7_UNORM_BLOCK);
            __FORMAT_CASE (FORMAT_BC7_SRGB, VK_FORMAT_BC7_SRGB_BLOCK);

            __FORMAT_CASE (FORMAT_D16_UNORM,          VK_FORMAT_D16_UNORM);
            __FORMAT_CASE (FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT);
            __FORMAT_CASE (FORMAT_D32_SFLOAT,         VK_FORMAT_D32_SFLOAT);
            __FORMAT_CASE (FORMAT_D24_UNORM_S8_UINT,  VK_FORMAT_D24_UNORM_S8_UINT);

            default:
                SLRD_DEBUG_CRIT ("getSLRDFormat: invalid enum");
                break;
        }
#undef __FORMAT_CASE

        return format;
    }

    slrd::Format getFittingDepthFormat (VKDevice *device, slrd::Format format) {
        SLRD_ASSERT (isDepthFormat (format));
        
        if (!hasStencil (format))
            return format;

        VkFormatProperties d24_props;
        vkGetPhysicalDeviceFormatProperties(device->getPhysicalDevice (),
                VK_FORMAT_D24_UNORM_S8_UINT, &d24_props);

        return d24_props.optimalTilingFeatures & VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT ?
            FORMAT_D24_UNORM_S8_UINT :
            FORMAT_D32_SFLOAT_S8_UINT;
    }
};
